### ISSUE TITLE
make dkms_build on Raspberry PI 4 throws error

### ISSUE THREAD

**Issue by alex-controlx** [icshwi/etherlabmaster#13]
**Describe the bug**
`make dkms_build` throws an error:
```
make[1]: Entering directory '/home/pi/etherlabmaster/etherlabmaster-code'
/usr/sbin/dkms build -m etherlabmaster -v 1.5.2

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make -j4 KERNELRELEASE=5.10.63-v7l+ -C /lib/modules/5.10.63-v7l+/build M=/var/lib/dkms/etherlabmaster/1.5.2/build modules....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.63-v7l+ (armv7l)
Consult /var/lib/dkms/etherlabmaster/1.5.2/build/make.log for more information.
make[1]: *** [etherlabmaster.Makefile:62: dkms_build] Error 10
make[1]: Leaving directory '/home/pi/etherlabmaster/etherlabmaster-code'
make: *** [/home/pi/etherlabmaster/configure/E3/RULES_ETHERLAB:96: dkms_build] Error 2
```

**To Reproduce**
1. Follow steps at [https://github.com/icshwi/etherlabmaster#installing-on-raspbian](https://github.com/icshwi/etherlabmaster#installing-on-raspbian)

**Expected behavior**
Completed without the error

**Desktop (please complete the following information):**
 - OS: 
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
 - Kernel Version: `Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`

**Comment by alex-controlx** [comment]
The log 
`cat /var/lib/dkms/etherlabmaster/1.5.2/build/make.log`
if helpful is below:
```
DKMS make.log for etherlabmaster-1.5.2 for kernel 5.10.63-v7l+ (armv7l)
Mon 13 Dec 15:03:58 AEDT 2021
make[2]: Entering directory '/usr/src/linux-headers-5.10.63-v7l+'
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/examples/mini/mini.o
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/master/cdev.o
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/devices/generic.o
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/master/coe_emerg_ring.o
/var/lib/dkms/etherlabmaster/1.5.2/build/master/cdev.c:91:14: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
   91 |     .fault = eccdev_vma_fault
      |              ^~~~~~~~~~~~~~~~
/var/lib/dkms/etherlabmaster/1.5.2/build/master/cdev.c:91:14: note: (near initialization for ‘eccdev_vm_ops.fault’)
cc1: some warnings being treated as errors
  LD [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/examples/mini/ec_mini.o
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/master/datagram.o
  CC [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/master/datagram_pair.o
make[4]: *** [scripts/Makefile.build:280: /var/lib/dkms/etherlabmaster/1.5.2/build/master/cdev.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  LD [M]  /var/lib/dkms/etherlabmaster/1.5.2/build/devices/ec_generic.o
make[3]: *** [scripts/Makefile.build:497: /var/lib/dkms/etherlabmaster/1.5.2/build/master] Error 2
make[2]: *** [Makefile:1825: /var/lib/dkms/etherlabmaster/1.5.2/build] Error 2
```

**Comment by alex-controlx** [comment]
This problem was fixed. Closing the issue.

Steps to fix it:
```
$ cd etherlabmaster
$ rm -rf etherlabmaster-code
$ git clone https://gitlab.com/etherlab.org/ethercat.git etherlabmaster-code
```

`make dkms_build` completed without errors
